# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarsystem',
            name='border',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='corridor',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='fringe',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='international',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='luminosity',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='regional',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='security',
        ),
    ]
