# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0003_solarsystem_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('volume', models.DecimalField(decimal_places=5, max_digits=25)),
            ],
        ),
    ]
