# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0004_itemtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='description',
        ),
    ]
