# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0003_solarsystem_security'),
        ('predds_tracker', '0002_locationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrecord',
            name='ship_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='ship_type_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='station_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='system',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eve_sde.SolarSystem'),
            preserve_default=False,
        ),
    ]
