# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0003_auto_20170121_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrecord',
            name='online',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationrecord',
            name='ship_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationrecord',
            name='ship_type_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
