# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predds_tracker', '0006_auto_20170121_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={},
        ),
        migrations.AlterModelManagers(
            name='character',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='character',
            name='email',
        ),
        migrations.RemoveField(
            model_name='character',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='character',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='character',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='password',
        ),
        migrations.RemoveField(
            model_name='character',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='character',
            name='username',
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationrecord',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predds_tracker.Character'),
        ),
    ]
