# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0008_auto_20170121_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='track',
            field=models.BooleanField(default=True),
        ),
    ]
