# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0011_systemstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatistic',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='eve_sde.SolarSystem'),
        ),
    ]
