# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0012_auto_20170123_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrecord',
            name='ship_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
