# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0005_auto_20160727_2333'),
        ('predds_tracker', '0013_locationrecord_ship_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.BooleanField(default=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth')),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='latest',
        ),
        migrations.RemoveField(
            model_name='character',
            name='track',
        ),
        migrations.AlterField(
            model_name='locationrecord',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predds_tracker.Alt'),
        ),
        migrations.AddField(
            model_name='alt',
            name='latest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='predds_tracker.LocationRecord'),
        ),
        migrations.AddField(
            model_name='alt',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alts', to=settings.AUTH_USER_MODEL),
        ),
    ]
