# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0014_auto_20170127_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alt',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
