# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0016_character_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
