# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0018_auto_20170127_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alt',
            options={'permissions': (('view_all_alts', 'Can view lists of all alts and their owners.'),)},
        ),
    ]
