# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0006_itemtype_description'),
        ('predds_tracker', '0019_auto_20170127_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationrecord',
            name='ship_type_id',
        ),
        migrations.AddField(
            model_name='locationrecord',
            name='ship_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eve_sde.ItemType'),
            preserve_default=False,
        ),
    ]
