# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0020_auto_20170127_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alliance_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='corporation_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
