# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0021_auto_20170127_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmetadata',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
