# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0023_auto_20170129_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
        migrations.AlterField(
            model_name='character',
            name='data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
    ]
