# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0024_auto_20170130_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={},
        ),
        migrations.AlterModelManagers(
            name='character',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='character',
            name='email',
        ),
        migrations.RemoveField(
            model_name='character',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='character',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='username',
        ),
        migrations.AlterField(
            model_name='alt',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
