# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:49
from __future__ import unicode_literals

from django.db import migrations
import predds_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0025_auto_20170130_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='character',
            managers=[
                ('objects', predds_tracker.models.UserManager()),
            ],
        ),
    ]
