# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0026_auto_20170130_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='password',
        ),
    ]
