# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0028_auto_20170130_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='track',
            field=models.BooleanField(default=True, help_text='If disabled, temporarily stop this character from being tracked.', verbose_name='Enable tracking'),
        ),
    ]
