# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predds_tracker', '0030_character_map_auto_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemstatistic',
            name='system',
        ),
        migrations.DeleteModel(
            name='SystemStatistic',
        ),
    ]
